// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im_proto_common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AudioMsgBriefInfo;
@class IMMessage;
@class IMMessageResponse;
@class MessageHead;
@class MsgHead;
@class MsgUserBriefInfo;
@class PicBriefInfo;
@class ProxyMsg;
@class PushMsg;
@class SendMsgReq;
@class SimpleUserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UpdateType

typedef GPB_ENUM(UpdateType) {
  UpdateType_UpdateFriendInvite = 0,
  UpdateType_UpdateGroupInvite = 1,
  UpdateType_UpdateFriendInfo = 2,
  UpdateType_UpdateGroupInfo = 3,
  UpdateType_UpdateDiscussionInfo = 4,
  UpdateType_UpdateAddressBookInfo = 5,
};

GPBEnumDescriptor *UpdateType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UpdateType_IsValidValue(int32_t value);

#pragma mark - Enum MsgType

/** œ˚œ¢¿‡–Õ */
typedef GPB_ENUM(MsgType) {
  MsgType_MsgText = 0,
  MsgType_MsgAudioBrief = 1,
  MsgType_MsgAudioComplete = 2,
  MsgType_MsgPicBrief = 3,
  MsgType_MsgPicComplete = 4,
  MsgType_MsgSys = 5,
  MsgType_MsgGame = 6,
  MsgType_MsgUpdate = 7,
  MsgType_MsgGameresult = 8,
};

GPBEnumDescriptor *MsgType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MsgType_IsValidValue(int32_t value);

#pragma mark - Enum IDType

/** œ˚œ¢∂‘œÛ¿‡–Õ */
typedef GPB_ENUM(IDType) {
  IDType_IdSingle = 0,
  IDType_IdGroup = 1,
  IDType_IdDiscussion = 2,
};

GPBEnumDescriptor *IDType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL IDType_IsValidValue(int32_t value);

#pragma mark - Enum FormatType

/** œ˚œ¢ÃÂµƒ∏Ò Ω */
typedef GPB_ENUM(FormatType) {
  FormatType_FormatProto = 0,
  FormatType_FormatJson = 1,
  FormatType_FormatXml = 2,
};

GPBEnumDescriptor *FormatType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL FormatType_IsValidValue(int32_t value);

#pragma mark - Enum EncryptMethod

/** œ˚œ¢ÃÂµƒº”√‹∑Ω∑® */
typedef GPB_ENUM(EncryptMethod) {
  EncryptMethod_EncryptNone = 0,
  EncryptMethod_EncryptDes = 1,
  EncryptMethod_EncryptTea = 2,
  EncryptMethod_EncryptAes = 3,
};

GPBEnumDescriptor *EncryptMethod_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL EncryptMethod_IsValidValue(int32_t value);

#pragma mark - Enum UserOnOffline

/** ”√ªß‘⁄œﬂ¿Îœﬂ◊¥Ã¨ */
typedef GPB_ENUM(UserOnOffline) {
  UserOnOffline_Offline = 0,
  UserOnOffline_Online = 1,
};

GPBEnumDescriptor *UserOnOffline_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UserOnOffline_IsValidValue(int32_t value);

#pragma mark - Enum ResultID

typedef GPB_ENUM(ResultID) {
  ResultID_ResultSuccess = 0,
  ResultID_ResultForbit = 1,
  ResultID_ResultFail = 2,
  ResultID_ResultGetfriendlistError = 3,
  ResultID_ResultUseroffline = 4,
  ResultID_ResultAlreadyFriend = 5,
  ResultID_ResultNotFriend = 6,
};

GPBEnumDescriptor *ResultID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ResultID_IsValidValue(int32_t value);

#pragma mark - Enum RegisterStatus

typedef GPB_ENUM(RegisterStatus) {
  RegisterStatus_RegisterNone = 0,
  RegisterStatus_RegisterAlready = 1,
};

GPBEnumDescriptor *RegisterStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RegisterStatus_IsValidValue(int32_t value);

#pragma mark - ImProtoCommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImProtoCommonRoot : GPBRootObject
@end

#pragma mark - MessageHead

typedef GPB_ENUM(MessageHead_FieldNumber) {
  MessageHead_FieldNumber_ClientVersion = 1,
  MessageHead_FieldNumber_Cid = 2,
  MessageHead_FieldNumber_BodyMessageFormat = 3,
  MessageHead_FieldNumber_EncryptMethod = 4,
  MessageHead_FieldNumber_MessageBodyName = 5,
};

/**
 * Õ®”√–≠“È«Î«ÛÕ∑≤ø
 **/
@interface MessageHead : GPBMessage

/** øÕªß∂À∞Ê±æ∫≈ */
@property(nonatomic, readwrite) int32_t clientVersion;

@property(nonatomic, readwrite) BOOL hasClientVersion;
@property(nonatomic, readwrite) int32_t cid;

@property(nonatomic, readwrite) BOOL hasCid;
/** œ˚œ¢ÃÂ∏Ò Ω "json" "protobuf" "xml"... */
@property(nonatomic, readwrite) FormatType bodyMessageFormat;

@property(nonatomic, readwrite) BOOL hasBodyMessageFormat;
/** œ˚œ¢ÃÂº”√‹∑Ω∑® "none" "tea" "xtea" "des"..... */
@property(nonatomic, readwrite) EncryptMethod encryptMethod;

@property(nonatomic, readwrite) BOOL hasEncryptMethod;
/** œ˚œ¢√˚≥∆£¨Õ¨œ˚œ¢√˚≥∆∂®“Â£¨»Á"TextMsgInfo"£¨"LoginRequest","HeartbeatRequest" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageBodyName;
/** Test to see if @c messageBodyName has been set. */
@property(nonatomic, readwrite) BOOL hasMessageBodyName;

@end

#pragma mark - IMMessage

typedef GPB_ENUM(IMMessage_FieldNumber) {
  IMMessage_FieldNumber_MessageHead = 1,
  IMMessage_FieldNumber_MessageBody = 2,
};

/**
 * –≠“È«Î«Û
 **/
@interface IMMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageHead *messageHead;
/** Test to see if @c messageHead has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHead;

/** ∂˛Ω¯÷∆œ˚œ¢ÃÂ */
@property(nonatomic, readwrite, copy, null_resettable) NSData *messageBody;
/** Test to see if @c messageBody has been set. */
@property(nonatomic, readwrite) BOOL hasMessageBody;

@end

#pragma mark - IMMessageResponse

typedef GPB_ENUM(IMMessageResponse_FieldNumber) {
  IMMessageResponse_FieldNumber_Result = 1,
  IMMessageResponse_FieldNumber_ResultInfo = 2,
};

@interface IMMessageResponse : GPBMessage

@property(nonatomic, readwrite) ResultID result;

@property(nonatomic, readwrite) BOOL hasResult;
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultInfo;
/** Test to see if @c resultInfo has been set. */
@property(nonatomic, readwrite) BOOL hasResultInfo;

@end

#pragma mark - MsgUserBriefInfo

typedef GPB_ENUM(MsgUserBriefInfo_FieldNumber) {
  MsgUserBriefInfo_FieldNumber_Cid = 1,
  MsgUserBriefInfo_FieldNumber_IdType = 2,
  MsgUserBriefInfo_FieldNumber_ExtInfo = 3,
};

@interface MsgUserBriefInfo : GPBMessage

/** ”√ªßid */
@property(nonatomic, readwrite) int32_t cid;

@property(nonatomic, readwrite) BOOL hasCid;
/** id¿‡–Õ£¨µ•»À£¨»¶◊”£¨Ã÷¬€◊È */
@property(nonatomic, readwrite) IDType idType;

@property(nonatomic, readwrite) BOOL hasIdType;
/** ∆‰À˚¿©’π–≈œ¢£¨øÕªß∂Àø…Õ∏¥´ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extInfo;
/** Test to see if @c extInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtInfo;

@end

#pragma mark - MsgHead

typedef GPB_ENUM(MsgHead_FieldNumber) {
  MsgHead_FieldNumber_SourceUserinfo = 1,
  MsgHead_FieldNumber_TargetUserinfo = 2,
  MsgHead_FieldNumber_MsgType = 3,
  MsgHead_FieldNumber_Timestamp = 4,
  MsgHead_FieldNumber_Sequence = 5,
};

@interface MsgHead : GPBMessage

/** ∑¢ÀÕ’ﬂµƒ–≈œ¢ */
@property(nonatomic, readwrite, strong, null_resettable) MsgUserBriefInfo *sourceUserinfo;
/** Test to see if @c sourceUserinfo has been set. */
@property(nonatomic, readwrite) BOOL hasSourceUserinfo;

/** Ω” ’’ﬂµƒ–≈œ¢ */
@property(nonatomic, readwrite, strong, null_resettable) MsgUserBriefInfo *targetUserinfo;
/** Test to see if @c targetUserinfo has been set. */
@property(nonatomic, readwrite) BOOL hasTargetUserinfo;

@property(nonatomic, readwrite) MsgType msgType;

@property(nonatomic, readwrite) BOOL hasMsgType;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) uint64_t sequence;

@property(nonatomic, readwrite) BOOL hasSequence;
@end

#pragma mark - Msg

typedef GPB_ENUM(Msg_FieldNumber) {
  Msg_FieldNumber_MsgHead = 1,
  Msg_FieldNumber_MsgInfo = 2,
  Msg_FieldNumber_RevInfo = 3,
};

@interface Msg : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MsgHead *msgHead;
/** Test to see if @c msgHead has been set. */
@property(nonatomic, readwrite) BOOL hasMsgHead;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgInfo;
/** Test to see if @c msgInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMsgInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *revInfo;
/** Test to see if @c revInfo has been set. */
@property(nonatomic, readwrite) BOOL hasRevInfo;

@end

#pragma mark - RegisterRequest

typedef GPB_ENUM(RegisterRequest_FieldNumber) {
  RegisterRequest_FieldNumber_ServerId = 1,
  RegisterRequest_FieldNumber_ServerType = 2,
};

@interface RegisterRequest : GPBMessage

@property(nonatomic, readwrite) int32_t serverId;

@property(nonatomic, readwrite) BOOL hasServerId;
@property(nonatomic, readwrite) int32_t serverType;

@property(nonatomic, readwrite) BOOL hasServerType;
@end

#pragma mark - RegisterResponse

typedef GPB_ENUM(RegisterResponse_FieldNumber) {
  RegisterResponse_FieldNumber_Result = 1,
};

@interface RegisterResponse : GPBMessage

@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - SimpleUserInfo

typedef GPB_ENUM(SimpleUserInfo_FieldNumber) {
  SimpleUserInfo_FieldNumber_Cid = 1,
  SimpleUserInfo_FieldNumber_Nickname = 2,
  SimpleUserInfo_FieldNumber_Sex = 3,
  SimpleUserInfo_FieldNumber_AvatarURL = 4,
};

@interface SimpleUserInfo : GPBMessage

@property(nonatomic, readwrite) int32_t cid;

@property(nonatomic, readwrite) BOOL hasCid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sex;
/** Test to see if @c sex has been set. */
@property(nonatomic, readwrite) BOOL hasSex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarURL;
/** Test to see if @c avatarURL has been set. */
@property(nonatomic, readwrite) BOOL hasAvatarURL;

@end

#pragma mark - UserInfo

typedef GPB_ENUM(UserInfo_FieldNumber) {
  UserInfo_FieldNumber_SimpleUserinfo = 1,
  UserInfo_FieldNumber_Mid = 2,
  UserInfo_FieldNumber_Regionid = 3,
  UserInfo_FieldNumber_ClientVersion = 4,
  UserInfo_FieldNumber_City = 5,
  UserInfo_FieldNumber_Status = 6,
};

@interface UserInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SimpleUserInfo *simpleUserinfo;
/** Test to see if @c simpleUserinfo has been set. */
@property(nonatomic, readwrite) BOOL hasSimpleUserinfo;

@property(nonatomic, readwrite) int32_t mid;

@property(nonatomic, readwrite) BOOL hasMid;
@property(nonatomic, readwrite) int32_t regionid;

@property(nonatomic, readwrite) BOOL hasRegionid;
@property(nonatomic, readwrite) int32_t clientVersion;

@property(nonatomic, readwrite) BOOL hasClientVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *city;
/** Test to see if @c city has been set. */
@property(nonatomic, readwrite) BOOL hasCity;

@property(nonatomic, readwrite) UserOnOffline status;

@property(nonatomic, readwrite) BOOL hasStatus;
@end

#pragma mark - SendMsgReq

typedef GPB_ENUM(SendMsgReq_FieldNumber) {
  SendMsgReq_FieldNumber_MsgHead = 1,
  SendMsgReq_FieldNumber_MsgInfo = 2,
  SendMsgReq_FieldNumber_SessionInfo = 3,
  SendMsgReq_FieldNumber_NickName = 4,
};

@interface SendMsgReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MsgHead *msgHead;
/** Test to see if @c msgHead has been set. */
@property(nonatomic, readwrite) BOOL hasMsgHead;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgInfo;
/** Test to see if @c msgInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMsgInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

@end

#pragma mark - SendMsgRes

typedef GPB_ENUM(SendMsgRes_FieldNumber) {
  SendMsgRes_FieldNumber_Res = 1,
  SendMsgRes_FieldNumber_SessionInfo = 2,
};

@interface SendMsgRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) IMMessageResponse *res;
/** Test to see if @c res has been set. */
@property(nonatomic, readwrite) BOOL hasRes;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@end

#pragma mark - SendMultiMsgReq

typedef GPB_ENUM(SendMultiMsgReq_FieldNumber) {
  SendMultiMsgReq_FieldNumber_SendMsgArray = 1,
};

@interface SendMultiMsgReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SendMsgReq*> *sendMsgArray;
/** The number of items in @c sendMsgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sendMsgArray_Count;

@end

#pragma mark - SyncMsgPush

typedef GPB_ENUM(SyncMsgPush_FieldNumber) {
  SyncMsgPush_FieldNumber_SyncNo = 1,
  SyncMsgPush_FieldNumber_Info = 2,
};

@interface SyncMsgPush : GPBMessage

@property(nonatomic, readwrite) uint64_t syncNo;

@property(nonatomic, readwrite) BOOL hasSyncNo;
@property(nonatomic, readwrite, copy, null_resettable) NSString *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - SyncMsgReq

typedef GPB_ENUM(SyncMsgReq_FieldNumber) {
  SyncMsgReq_FieldNumber_SyncNo = 1,
  SyncMsgReq_FieldNumber_Info = 2,
};

@interface SyncMsgReq : GPBMessage

@property(nonatomic, readwrite) uint64_t syncNo;

@property(nonatomic, readwrite) BOOL hasSyncNo;
@property(nonatomic, readwrite, copy, null_resettable) NSString *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - SyncMsgRes

typedef GPB_ENUM(SyncMsgRes_FieldNumber) {
  SyncMsgRes_FieldNumber_MsgsArray = 1,
  SyncMsgRes_FieldNumber_SyncNo = 2,
  SyncMsgRes_FieldNumber_Info = 3,
};

@interface SyncMsgRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PushMsg*> *msgsArray;
/** The number of items in @c msgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@property(nonatomic, readwrite) uint64_t syncNo;

@property(nonatomic, readwrite) BOOL hasSyncNo;
@property(nonatomic, readwrite, copy, null_resettable) NSString *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - SyncMsgAck

typedef GPB_ENUM(SyncMsgAck_FieldNumber) {
  SyncMsgAck_FieldNumber_SyncNo = 1,
  SyncMsgAck_FieldNumber_Info = 2,
};

@interface SyncMsgAck : GPBMessage

@property(nonatomic, readwrite) uint64_t syncNo;

@property(nonatomic, readwrite) BOOL hasSyncNo;
@property(nonatomic, readwrite, copy, null_resettable) NSString *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - PushMsg

typedef GPB_ENUM(PushMsg_FieldNumber) {
  PushMsg_FieldNumber_MsgHead = 1,
  PushMsg_FieldNumber_MsgInfo = 2,
  PushMsg_FieldNumber_SessionInfo = 3,
};

@interface PushMsg : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MsgHead *msgHead;
/** Test to see if @c msgHead has been set. */
@property(nonatomic, readwrite) BOOL hasMsgHead;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msgInfo;
/** Test to see if @c msgInfo has been set. */
@property(nonatomic, readwrite) BOOL hasMsgInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@end

#pragma mark - PushMsgRes

typedef GPB_ENUM(PushMsgRes_FieldNumber) {
  PushMsgRes_FieldNumber_Result = 1,
  PushMsgRes_FieldNumber_SessionInfo = 2,
};

@interface PushMsgRes : GPBMessage

@property(nonatomic, readwrite) ResultID result;

@property(nonatomic, readwrite) BOOL hasResult;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@end

#pragma mark - PushMultiMsg

typedef GPB_ENUM(PushMultiMsg_FieldNumber) {
  PushMultiMsg_FieldNumber_PushMsgArray = 1,
  PushMultiMsg_FieldNumber_SessionInfo = 2,
};

@interface PushMultiMsg : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PushMsg*> *pushMsgArray;
/** The number of items in @c pushMsgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pushMsgArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@end

#pragma mark - PushMultiMsgRes

typedef GPB_ENUM(PushMultiMsgRes_FieldNumber) {
  PushMultiMsgRes_FieldNumber_Result = 1,
  PushMultiMsgRes_FieldNumber_SessionInfo = 2,
};

@interface PushMultiMsgRes : GPBMessage

@property(nonatomic, readwrite) ResultID result;

@property(nonatomic, readwrite) BOOL hasResult;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionInfo;
/** Test to see if @c sessionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasSessionInfo;

@end

#pragma mark - TextMsgInfo

typedef GPB_ENUM(TextMsgInfo_FieldNumber) {
  TextMsgInfo_FieldNumber_Msg = 1,
};

/**
 * Œƒ±æœ˚œ¢
 **/
@interface TextMsgInfo : GPBMessage

/** œ˚œ¢ÃÂ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - AudioMsgBriefInfo

typedef GPB_ENUM(AudioMsgBriefInfo_FieldNumber) {
  AudioMsgBriefInfo_FieldNumber_AudioLength = 1,
  AudioMsgBriefInfo_FieldNumber_AudioSize = 2,
  AudioMsgBriefInfo_FieldNumber_URL = 3,
};

/**
 * “Ù∆µŒƒº˛µƒÀı¬‘–≈œ¢
 **/
@interface AudioMsgBriefInfo : GPBMessage

/**  ±≥§, µ•Œª «√Î */
@property(nonatomic, readwrite) int32_t audioLength;

@property(nonatomic, readwrite) BOOL hasAudioLength;
/** ¥Û–°, µ•Œª «◊÷Ω⁄ */
@property(nonatomic, readwrite) int32_t audioSize;

@property(nonatomic, readwrite) BOOL hasAudioSize;
/** “Ù∆µµÿ÷∑ªÚŒƒº˛¥Ê¥¢key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

#pragma mark - AudioMsgCompleteInfo

typedef GPB_ENUM(AudioMsgCompleteInfo_FieldNumber) {
  AudioMsgCompleteInfo_FieldNumber_BriefAudioInfo = 1,
  AudioMsgCompleteInfo_FieldNumber_AudioData = 2,
};

/**
 * “Ù∆µŒƒº˛µƒÕÍ’˚œ˚œ¢
 **/
@interface AudioMsgCompleteInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AudioMsgBriefInfo *briefAudioInfo;
/** Test to see if @c briefAudioInfo has been set. */
@property(nonatomic, readwrite) BOOL hasBriefAudioInfo;

/** “Ù∆µ∂˛Ω¯÷∆ ˝æ› */
@property(nonatomic, readwrite, copy, null_resettable) NSData *audioData;
/** Test to see if @c audioData has been set. */
@property(nonatomic, readwrite) BOOL hasAudioData;

@end

#pragma mark - PicBriefInfo

typedef GPB_ENUM(PicBriefInfo_FieldNumber) {
  PicBriefInfo_FieldNumber_PicSize = 1,
  PicBriefInfo_FieldNumber_Height = 2,
  PicBriefInfo_FieldNumber_Width = 3,
  PicBriefInfo_FieldNumber_ThumbleURL = 4,
  PicBriefInfo_FieldNumber_URL = 5,
};

/**
 * Õº∆¨Œƒº˛µƒÀı¬‘–≈œ¢
 **/
@interface PicBriefInfo : GPBMessage

/** Õº∆¨¥Û–° */
@property(nonatomic, readwrite) int32_t picSize;

@property(nonatomic, readwrite) BOOL hasPicSize;
@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite) BOOL hasHeight;
@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) BOOL hasWidth;
/** Àı¬‘Õº */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbleURL;
/** Test to see if @c thumbleURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbleURL;

/** ¥ÛÕºµÿ÷∑ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

#pragma mark - PicCompleteInfo

typedef GPB_ENUM(PicCompleteInfo_FieldNumber) {
  PicCompleteInfo_FieldNumber_PicBriefInfo = 1,
  PicCompleteInfo_FieldNumber_PicData = 2,
};

/**
 * Õº∆¨Œƒº˛µƒÕÍ’˚–≈œ¢
 **/
@interface PicCompleteInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PicBriefInfo *picBriefInfo;
/** Test to see if @c picBriefInfo has been set. */
@property(nonatomic, readwrite) BOOL hasPicBriefInfo;

/** Õº∆¨∂˛Ω¯÷∆ ˝æ› */
@property(nonatomic, readwrite, copy, null_resettable) NSData *picData;
/** Test to see if @c picData has been set. */
@property(nonatomic, readwrite) BOOL hasPicData;

@end

#pragma mark - SystemMsgInfo

typedef GPB_ENUM(SystemMsgInfo_FieldNumber) {
  SystemMsgInfo_FieldNumber_Msg = 1,
};

/**
 * œµÕ≥œ˚œ¢
 **/
@interface SystemMsgInfo : GPBMessage

/** œ˚œ¢ÃÂ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - GameMsgInfo

typedef GPB_ENUM(GameMsgInfo_FieldNumber) {
  GameMsgInfo_FieldNumber_GameData = 1,
};

/**
 * ≈∆æ÷œ˚œ¢
 **/
@interface GameMsgInfo : GPBMessage

/** ≈∆æ÷◊‘∂®“Â ˝æ›£¨øÕªß∂À◊‘––Ω‚Œˆ */
@property(nonatomic, readwrite, copy, null_resettable) NSData *gameData;
/** Test to see if @c gameData has been set. */
@property(nonatomic, readwrite) BOOL hasGameData;

@end

#pragma mark - UserLoginReq

typedef GPB_ENUM(UserLoginReq_FieldNumber) {
  UserLoginReq_FieldNumber_ClientVersion = 1,
  UserLoginReq_FieldNumber_Sig = 2,
  UserLoginReq_FieldNumber_ExtInfo = 3,
};

/**
 * øÕªß∂Àµ«¬Ω«Î«Û
 **/
@interface UserLoginReq : GPBMessage

/** øÕªß∂À∞Ê±æ∫≈ */
@property(nonatomic, readwrite) int32_t clientVersion;

@property(nonatomic, readwrite) BOOL hasClientVersion;
/** øÕªß∂À«©√˚ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sig;
/** Test to see if @c sig has been set. */
@property(nonatomic, readwrite) BOOL hasSig;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extInfo;
/** Test to see if @c extInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtInfo;

@end

#pragma mark - UserLoginRes

typedef GPB_ENUM(UserLoginRes_FieldNumber) {
  UserLoginRes_FieldNumber_Result = 1,
  UserLoginRes_FieldNumber_Error = 2,
  UserLoginRes_FieldNumber_Extinfo = 3,
};

/**
 * ∑˛ŒÒ∆˜µ«¬ΩœÏ”¶
 **/
@interface UserLoginRes : GPBMessage

@property(nonatomic, readwrite) ResultID result;

@property(nonatomic, readwrite) BOOL hasResult;
/** øÕªß∂À¥ÌŒÛ–≈œ¢ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** ∑˛ŒÒ∆˜∏¯øÕªß∂Àµƒ±£¡Ù◊÷∂Œ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extinfo;
/** Test to see if @c extinfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtinfo;

@end

#pragma mark - HeartbeatRequest

typedef GPB_ENUM(HeartbeatRequest_FieldNumber) {
  HeartbeatRequest_FieldNumber_Time = 1,
};

/**
 * øÕªß∂À∑¢ÀÕ–ƒÃ¯∞¸
 **/
@interface HeartbeatRequest : GPBMessage

/** øÕªß∂À ±º‰ */
@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@end

#pragma mark - HeartbeatResponse

typedef GPB_ENUM(HeartbeatResponse_FieldNumber) {
  HeartbeatResponse_FieldNumber_Result = 1,
};

@interface HeartbeatResponse : GPBMessage

@property(nonatomic, readwrite) ResultID result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - ProxyMsg

typedef GPB_ENUM(ProxyMsg_FieldNumber) {
  ProxyMsg_FieldNumber_SourceId = 1,
  ProxyMsg_FieldNumber_TargetId = 2,
  ProxyMsg_FieldNumber_Msg = 3,
};

@interface ProxyMsg : GPBMessage

@property(nonatomic, readwrite) int32_t sourceId;

@property(nonatomic, readwrite) BOOL hasSourceId;
@property(nonatomic, readwrite) int32_t targetId;

@property(nonatomic, readwrite) BOOL hasTargetId;
@property(nonatomic, readwrite, strong, null_resettable) IMMessage *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - ProxyMultiMsg

typedef GPB_ENUM(ProxyMultiMsg_FieldNumber) {
  ProxyMultiMsg_FieldNumber_MsgsArray = 1,
};

@interface ProxyMultiMsg : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProxyMsg*> *msgsArray;
/** The number of items in @c msgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@end

#pragma mark - ProxyMultiMsgRes

typedef GPB_ENUM(ProxyMultiMsgRes_FieldNumber) {
  ProxyMultiMsgRes_FieldNumber_Res = 1,
};

@interface ProxyMultiMsgRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) IMMessageResponse *res;
/** Test to see if @c res has been set. */
@property(nonatomic, readwrite) BOOL hasRes;

@end

#pragma mark - NotifyBekicked

typedef GPB_ENUM(NotifyBekicked_FieldNumber) {
  NotifyBekicked_FieldNumber_Time = 1,
  NotifyBekicked_FieldNumber_RemoteIp = 2,
};

@interface NotifyBekicked : GPBMessage

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *remoteIp;
/** Test to see if @c remoteIp has been set. */
@property(nonatomic, readwrite) BOOL hasRemoteIp;

@end

#pragma mark - UpdateInfo

typedef GPB_ENUM(UpdateInfo_FieldNumber) {
  UpdateInfo_FieldNumber_UpdateParams = 1,
  UpdateInfo_FieldNumber_UpdateType = 2,
};

@interface UpdateInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *updateParams;
/** Test to see if @c updateParams has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateParams;

@property(nonatomic, readwrite) UpdateType updateType;

@property(nonatomic, readwrite) BOOL hasUpdateType;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
